server:
  port: 8080
  servlet:
    context-path: /api/data-aggregator-service
spring:
  datasource:
    url:url: jdbc:redshift://medi-workgroup.640168455114.eu-north-1.redshift-serverless.amazonaws.com:5439/dev
    username: admin
    password: 'VCIGOzwbbk081*!'
